sudo: required
services:
  - docker
language: ruby
cache: bundler
addons:
  postgresql: "9.6"
rvm:
  - 2.3.1
before_script:
  - cp config/database.yml{.sample,}
  - bundle exec rake db:create db:test:prepare
after_success:
  - ./scripts/build
notifications:
  slack:
    secure: 0G/Se8dzkHjvMWbGi5GSBKXdz6paSgBmgHeIxCPT/9i5Msz2GYM0WHPXlsu87oCBIa07pqnP9vI/tfEaK2q+pvC2LMCvC994VlIxwVfgxcGPp4QmZf1sm5lbgRxoaKHLOWPRoKGkvZ08hkuJv65TbUcp6DdD1/nOQAwbf7e25kmKkkNw0S+g+5Pjq0tCSzlGN6qFV+hfhmEeSNg9Q4iy5GSmB5IYOqRB4D0qVRsOYClZ1fygw3+qY+FwpGVuVdb7SjpqSs7/cWbeV0X9erCNqOgI6/PlfniC9kkMmhCxo7eO46fK1rsRr8lb3DbF8bxwjTcVqdRuCxA8dOMWIZvINkdyXcyzBReE4V6wa3SgTIhifU5b7euUs3x93cfA4US0iIl4v9zkMvUuXtmjLf0I5tSB+gkYir6Z8GmOBsmDEVWvys6DRovAXkhZH/Gfy9n9Bl/2sztH9dqdBulNVqCkYltsb9RhidLrF64EQMJ/sBsvx4zTcd6ac7sdfuUhzQCWcWc1IsSf34PGYglLIyWUFUD1S5k75RUfQuk8qTLDkQp9gwDIzH3ZgCMucM3x/aSpUxuAtzPCmIh3r67kqi8w762ODAeILBkWUSOp8/Mvg6MG7IUXs6myNt8HSKu3z2+J1FfbMEEWTwIZ1wKR4rMe6hMYJw9/vbZYj+7hfhoCCB0=
