version: '2'
services:
  db:
    image: postgres:9.4
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
  redis:
    image: redis:3.0.5
    ports:
      - "6379:6379"
    volumes:
      - redis:/var/lib/redis/data
  web:
    build:
      dockerfile: "ops/dev/Dockerfile"
      context: .
    ports:
      - "3000:3000"
      - "9876:9876"
    env_file:
      - .env
      - .env.local
    depends_on:
      - db
    links:
      - redis
      - mail
      - bridge
    volumes_from:
      - bundle
    volumes:
      - .:/app
      - ../:/src
  # test:
  #   build:
  #     context: .
  #     dockerfile: "ops/test/Dockerfile"
  #   env_file:
  #     - .env
  #     - .env.test
  #     - .env.local
  #   depends_on:
  #     - db
  #     - redis
  #   volumes_from:
  #     - bundle
  #   volumes:
  #     - .:/app
  #     - ../:/src
  sidekiq:
    build:
      dockerfile: "ops/dev/Dockerfile"
      context: .
    command: bundle exec sidekiq -C config/sidekiq.yml
    depends_on:
      - db
    links:
      - redis
      - mail
      - bridge
    env_file:
      - .env
      - .env.local
    volumes_from:
      - bundle
    volumes:
      - ./:/app
      - ../:/src
  bundle:
    image: busybox
    volumes:
      - /bundle
  mail:
    image: djfarrelly/maildev
    ports:
      - "1080:80"
    # NOTE: no need to expose 25 because its image already calls EXPOSE 25
    #
  bridge:
    image: bloomsolutions/stellar-bridge:v1
    ports:
      - "8001:8001"
    depends_on:
      - bridge_db
    env_file:
      - .env.bridge
      - .env.bridge.local
  bridge_db:
    image: postgres:9.5
    expose:
      - "5432"
    volumes:
      - bridge_db:/var/lib/postgresql/data

volumes:
  redis:
  postgres:
  bundle:
  src:
  bridge_db:
