defaults: &defaults
  port: <%= ENV["RAILS_PORT"] || 80 %>
  host: <%= ENV["RAILS_HOST"] || "localhost" %>
  protocol: "http"
  stellar_lookout_url: <%= ENV["STELLAR_LOOKOUT_URL"] %>
  bloom_net_issuer_account: <%= ENV["BLOOM_NET_ISSUER_ACCOUNT"] %>
  bloom_net_center:
    host: <%= ENV["BLOOM_NET_CENTER_HOST"] %>
    token: <%= ENV["BLOOM_NET_CENTER_TOKEN"] %>
    secret: <%= ENV["BLOOM_NET_CENTER_SECRET"] %>
  bloom_net_address: <%= ENV["BLOOM_NET_ADDRESS"] %>
  bloom_net_seed: <%= ENV["BLOOM_NET_SEED"] %>
  smtp:
    username: <%= ENV["SMTP_USERNAME"] %>
    password: <%= ENV["SMTP_PASSWORD"] %>
    address: <%= ENV["SMTP_ADDRESS"] %>
    port: <%= ENV["SMTP_PORT"] %>

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
  protocol: "https"
